markdown:
  kramdown

kramdown:
  input: GFM
  hard_wrap: false

baseurl:

liquid:
  error_mode: strict

sass:
  style: compressed

paginate: 5
paginate_path: "/blog/page:num/"

excerpt_separator: <!--end_excerpt-->

collections:
  docs:
    output: true
  faq:
    output: false
  glossary:
    output: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
