markdown:
  kramdown

kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

baseurl:
url: https://istio.io

highlighter: rouge

liquid:
  error_mode: strict

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  blanklines: false
  profile: false

collections:
  faq:
    output: false
  glossary:
    output: false
  blog:
    output: true
  docs:
    output: true
  help:
    output: true
  about:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "about"
    values:
      layout: "about"
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: "help"
    values:
      layout: "help"
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - CNAME
  - CONTRIBUTING.md
  - .gitignore
  - .gitmodules
  - Vagrantfile
  - .vagrant
  - _blog/posts/post.md.template
  - _docs/concepts/concept.md.template
  - _docs/tasks/task.md.template
  - _docs/guides/sample.md.template
  - _docs/reference/reference.md.template
  - _docs/setup/setup.md.template
  - scripts/
  - Rakefile
  - Jenkinsfile
  - repos/*.html
  - repos/*.md
  - vendor/
  - js/misc.js
  - js/styleSwitcher.js
  - firebase.json
  - _rakesite
  - mdl_style.rb

repository:
  istio/istio.github.io
