defaultContentLanguage = "en"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Istio"
uglyURLs = false
enableRobotsTXT = true
googleAnalytics = "UA-98480406-1"
pluralizeListTitles = false
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
anchor = "smart"
enableGitInfo = true
enableEmoji = true
buildFuture = true

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
	hrefTargetBlank = false
    angledQuotes = false
    latexDashes = true
    extensions = [""]

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = true

    # Will lower case keywords in both queries and in the indexes.
    toLower = false

    [[related.indices]]
        name = "keywords"
        weight = 150

    [[related.indices]]
        name  = "tags"
        weight = 100

# internationalization
[languages]
  [languages.zh]
    contentDir = "content_zh"
  [languages.en]
    contentDir = "content"
