defaultContentLanguage = "en"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Istio"
uglyURLs = false
enableRobotsTXT = true
pluralizeListTitles = false
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
anchor = "smart"
enableGitInfo = true
enableEmoji = false
buildFuture = true
staticDir = ["static", "generated"]

# we use Netlify server-side redirects instead of generated aliases
disableAliases = true

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackfriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
    extensions = [""]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2

[mediaTypes]
    [mediaTypes."text/netlify"]
        delimiter = ""

[outputs]
  home = ["HTML", "RSS", "REDIR", "JSON"]
  section = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"
    [outputFormats.REDIR]
        mediatype = "text/netlify"
        baseName = "_redirects"
        isPlainText = true
        notAlternative = true
    [outputFormats.JSON]
        baseName = "_tracked_pages"

[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = true

    # Will lower case keywords in both queries and in the indexes.
    toLower = false

    [[related.indices]]
        name = "keywords"
        weight = 150

    [[related.indices]]
        name  = "tags"
        weight = 100

# internationalization
[languages]
    [languages.zh]
        contentDir = "content/zh"
    [languages.en]
        contentDir = "content/en"
    [languages.pt-br]
        contentDir = "content/pt-br"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About section"
    url = "/about/"
    weight = 1
    
    [[menu.main]]
      identifier = "service-mesh"
      name = "Service mesh"
      title = "Service mesh"
      url = "/about/service-mesh"
      parent = "about"
      weight = 1

    [[menu.main]]
      identifier = "use-cases"
      name = "Use cases"
      title = "Use cases"
      url = "/about/use-cases"
      parent = "about"
      weight = 2

    [[menu.main]]
      identifier = "case-studies"
      name = "Case studies"
      title = "Case studies"
      url = "/about/case-studies"
      parent = "about"
      weight = 3

    [[menu.main]]
      identifier = "partners"
      name = "Partners"
      title = "Partners"
      url = "/about/partners"
      parent = "about"
      weight = 4

    [[menu.main]]
      identifier = "deployment-guides"
      name = "Deployment guides"
      title = "Deployment guides"
      url = "/about/deployment-guides"
      parent = "about"
      weight = 5

    [[menu.main]]
      identifier = "faq"
      name = "FAQ"
      title = "FAQ"
      url = "/about/faq"
      parent = "about"
      weight = 6

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Istio Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "get-involved"
    name = "Get involved"
    title = "Get involved"
    url = "/get-involved/"
    weight = 3

  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    title = "Documentation"
    url = "/docs/"
    weight = 4
