[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.102.3"
    NODE_VERSION = "18.2.0"
    BUILD_WITH_CONTAINER = "0"
    GO_VERSION = "1.19.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
