[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.139.3"
    NODE_VERSION = "20.18.0"
    BUILD_WITH_CONTAINER = "0"
    GO_VERSION = "1.23.3"
    PYTHON_VERSION = "3.12.3"
    RUBY_VERSION = "3.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
