[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.118.2"
    NODE_VERSION = "18.17.1"
    BUILD_WITH_CONTAINER = "0"
    GO_VERSION = "1.21.1"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "3.0.6"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
