version: 2
jobs:
  build:
    docker:
      - image: gcr.io/istio-testing/website-builder:2018-09-15

    working_directory: ~/site

    steps:
      - checkout

      - run:
          name: Generating Site
          command: scripts/gen_site.sh "" -no_minify

      - run:
          name: Running Linters
          command: scripts/lint_site.sh
